on:
  push:
    branches:
      - "main"
      - "develop"

env:
  # Examples indicated in comments
  FLOWNAME: myflow
  DEPLOYMENTNAME: demo
  ECRNAME: 330830921905.dkr.ecr.us-east-2.amazonaws.com/gh-test
  INFRA: kubernetes-job/gh-test
  # SCHEDULE: {your_schedule} # cron "0 0 * * *"
  STORAGE: s3/gh-test
  FILESYSTEM_EXTRAS: s3fs

jobs:
  build:
    name: deploy flow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: divideprojects/poetry-export-requirements-action@v1
        with:
          without-hashes: true
          outfile-name: requirements.txt
      # Extract the current branch name to reference Blocks corresponding to this environment
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.0
      - name: Python dependencies
        run: |
          pip install -U wheel pip $FILESYSTEM_EXTRAS
          pip install -r requirements.txt
      - name: Prefect Cloud login
        run: |
          prefect config set PREFECT_API_KEY=${{ secrets.PREFECT_API_KEY }}
          prefect config set PREFECT_API_URL=${{ secrets.PREFECT_API_URL }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: int128/create-ecr-repository-action@v1
        id: ecr
        with:
          repository: ${{ env.ECRNAME }}
      - name: Push to container registry
        run: |
          docker build . --tag ${{ env.ECRNAME }}:latest -f ./Dockerfile
          docker push ${{ env.ECRNAME }}:latest
      # Branch based logic to submit flows to different workqueues
      - if: github.ref == 'refs/heads/main'
        name: Build and apply Prefect deployment
        run: prefect deployment build ./flow/flow.py:$FLOWNAME -n $DEPLOYMENT_NAME -sb $STORAGE -ib $INFRA -q prod --apply
      - if: github.ref != 'refs/heads/main'
        name: Build and apply Prefect deployment
        run: prefect deployment build ./flow/flow.py:$FLOWNAME -n $DEPLOYMENT_NAME -sb $STORAGE -ib $INFRA -q dev --apply
      # In order to attach schedules please attached a flag- cron, interval or rrule
      # Example- prefect deployment build demo.py:pipeline -n etl --cron "0 0 * * *"